# Generated by Django 3.0.5 on 2023-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230110_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='accounts.Tags'),
        ),
    ]
